spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://116.62.42.66:3306/A12?useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      suffix: .html
      prefix: /
